/**:
  ros__parameters:
    start:
      x: 4.5
      y: 0.5
      theta: 0.0
    goal:
      x: 0.5
      y: 4.5
      theta: 130.0
    # goal:
    #   x: 10.0
    #   y: 490.0
    #   theta: 130.0
    robot:
      width: 0.3
      length: 0.2
    # map_name: "map_500x1000"
    map_name: "map_5x10"
